name: ghpages

on:
  push:
    branches: [ main ]

env:
  php_version: 8.1

jobs:

  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ghpages
      cancel-in-progress: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
      - name: Generate static pages
        run: |
          composer global require abenevaut/laravel-one
          laravel-one generate https://www.antoine-sanchez.com
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
